# Stubs for object_models (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def asdict(*args, **kwargs) -> Dict: ...
def insert_values(object): ...
def list_asdict(in_list): ...
def insert_filter(attribute, value): ...

class Contact:
    id = ...  # type: Any
    name = ...  # type: Any
    email = ...  # type: Any
    phone = ...  # type: Any
    active = ...  # type: Any
    model_type = ...  # type: str
    def __init__(*args, **kwargs) -> None: ...

class ContactGroup:
    id = ...  # type: Any
    name = ...  # type: Any
    active = ...  # type: Any
    model_type = ...  # type: str
    def __init__(*args, **kwargs) -> None: ...

class ActiveMonitor:
    id = ...  # type: Any
    def_id = ...  # type: Any
    state = ...  # type: Any
    state_ts = ...  # type: Any
    msg = ...  # type: Any
    alert_id = ...  # type: Any
    deleted = ...  # type: Any
    checks_enabled = ...  # type: Any
    alerts_enabled = ...  # type: Any
    args = ...  # type: Any
    model_type = ...  # type: str
    def __init__(*args, **kwargs) -> None: ...

class ActiveMonitorArg:
    id = ...  # type: Any
    monitor_id = ...  # type: Any
    name = ...  # type: Any
    value = ...  # type: Any
    model_type = ...  # type: str
    def __init__(*args, **kwargs) -> None: ...

class ActiveMonitorAlert:
    id = ...  # type: Any
    monitor_id = ...  # type: Any
    start_ts = ...  # type: Any
    end_ts = ...  # type: Any
    alert_msg = ...  # type: Any
    model_type = ...  # type: str
    monitor = ... # type: Any
    def __init__(*args, **kwargs) -> None: ...

class ActiveMonitorDef:
    id = ...  # type: Any
    name = ...  # type: Any
    description = ...  # type: Any
    active = ...  # type: Any
    cmdline_filename = ...  # type: Any
    cmdline_args_tmpl = ...  # type: Any
    description_tmpl = ...  # type: Any
    args = ...  # type: Any
    model_type = ...  # type: str
    def __init__(*args, **kwargs) -> None: ...

class ActiveMonitorDefArg:
    id = ...  # type: Any
    active_monitor_def_id = ...  # type: Any
    name = ...  # type: Any
    display_name = ...  # type: Any
    description = ...  # type: Any
    required = ...  # type: Any
    default_value = ...  # type: Any
    model_type = ...  # type: str
    def __init__(*args, **kwargs) -> None: ...

class ObjectMetadata:
    object_type = ...  # type: Any
    object_id = ...  # type: Any
    key = ...  # type: Any
    value = ...  # type: Any
    model_type = ...  # type: str
    def __init__(*args, **kwargs) -> None: ...

class ObjectBindata:
    object_type = ...  # type: Any
    object_id = ...  # type: Any
    key = ...  # type: Any
    value = ...  # type: Any
    model_type = ...  # type: str
    def __init__(*args, **kwargs) -> None: ...

class MonitorGroup:
    id = ...  # type: Any
    parent_id = ...  # type: Any
    name = ...  # type: Any
    model_type = ...  # type: str
    def __init__(*args, **kwargs) -> None: ...
